### ISSUE TITLE
师傅好，想问问有没有ubuntu+mysql的模板？

### ISSUE THREAD

**Issue by DetLFY** [CTF-Archives/ctf-docker-template#1]
制作webpwn题需要。

**Comment by Randark-JMT** [comment]
只是需要Ubuntu环境中存在一个Mysql服务吗，需要指定特定版本吗

**Comment by DetLFY** [comment]
> 

Ubuntu需要的是18.04版本的，MySQL最好是5.7版本的。我尝试过直接在dockerfile里添加mysql服务，但是apt-get的时候会报错，大概好像是会写/proc里但是没有权限。

**Comment by Randark-JMT** [comment]
问题比我想象的要难，因为docker终究还是一个容器化技术，没办法做到完全的虚拟机内Linux的感受，很多操作要做手动化。。😭😭😭

**Comment by Randark-JMT** [comment]
在commit 8202626c2044793acf9416ce643b70acd268db7a 中，我基于php官方仓库做了一定的魔改，手动修改了版本，并且nop掉了部分gpg验证公钥部分，并在魔改的php镜像上加上了CTF Training（感谢赵总）所实现的Mysql安装部分

但是很可惜其实在php安装部分就卡住了（由于某个dev依赖库要求的最低版本达不到18.04，而且部分库安装的时候要求交互式设置时区），所以算是个失败的失败品，mark一下，万一后面有人想到怎么魔改了呢

**Comment by Randark-JMT** [comment]
暂时挂起此issue
