### ISSUE TITLE
The content of the flag file is incorrectly written

### ISSUE THREAD

**Issue by gtg2619** [CTF-Archives/ctf-docker-template#2]
# templates
web-nginx-php73

# environment
Ubuntu 22.04
Docker Engine Version
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:57 2023
 OS/Arch:           linux/amd64
 Context:           default
  GitCommit:        de40ad0

# details
Use the default template file to build the image and run
![image](https://github.com/CTF-Archives/ctf-docker-template/assets/110759348/cba4ead4-7441-441e-a19d-aaf8aa2da9ad)

After using the exec link, I see that the /flag file is empty
![image](https://github.com/CTF-Archives/ctf-docker-template/assets/110759348/13c13043-a5c5-4461-8d6d-74b6cb503a49)

However, manually executing `/docker-entrypoint.sh` after connection can write the `/flag` correctly
![image](https://github.com/CTF-Archives/ctf-docker-template/assets/110759348/8c903fd4-7b5c-46c2-b689-02ddb8b13ed0)

So I think it may be due to some write conflict with the underlying image, or CMD command conflict

**Comment by Randark-JMT** [comment]
This is an interesting problem because /flag is not null once the -e parameter is passed in with a flag

**Comment by Randark-JMT** [comment]
抱歉，这个问题有一点复杂，英文跟不上了（）

这个问题由基础镜像[base_image_nginx_php_73 ](https://github.com/CTFTraining/base_image_nginx_php_73) 所导致的

[base_image_nginx_php_73/_files/flag.sh](https://github.com/CTFTraining/base_image_nginx_php_73/blob/master/_files/flag.sh)这里可以看到，镜像入口点将FLAG变量强制覆写了一遍，所以在没有传入FLAG环境变量的情况下，会将原本CMD执行点的脚本所写入的flag重新覆写掉，即为空值

通过重新控制ENTRYPOINT镜像入口点，可以一定程度上解决这个问题，但是感觉不太优雅，后期会通过更改基础镜像来解决这个问题

**Comment by Randark-JMT** [comment]
此问题已在7c9f8832f80b323acb2b5f9184e9dafc0dbc457a提交中修复

**Comment by ProbiusOfficial** [comment]
呜呜呜 橘墨yyds！tql呜呜呜呜

**Comment by Randark-JMT** [comment]
> 呜呜呜 橘墨yyds！tql呜呜呜呜

论强，还得看探姬😥😥😥
